server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: spring
  main:
    banner-mode: off

logging:
  pattern:
    file: "%d{dd-MM HH:mm} - %-5level - %logger{1} - %msg%n"
  file:
    name: logs/app.log
  level:
    root: WARN
    org:
      hibernate: error
      springframework:
        test: WARN
        boot: WARN
    com:
      mak: INFO